Highcharts.mapDataIndex['Denmark'] = {
  'Nordjylland, admin2': 'countries/dk/dk-3568-all.js',
  'Midtjylland, admin2': 'countries/dk/dk-6326-all.js',
  'Syddanmark, admin2': 'countries/dk/dk-3564-all.js',
  'Sjælland, admin2': 'countries/dk/dk-3563-all.js',
  'Hovedstaden, admin2': 'countries/dk/dk-6325-all.js',
};

Highcharts.mapDataIndex['Sweden'] = {
  "Blekinge, admin2": "countries/se/se-bl-all.js",
  "Dalarna, admin2": "countries/se/se-ko-all.js",
  "Gävleborg, admin2": "countries/se/se-gv-all.js",
  "Gotland, admin2": "countries/se/se-gt-all.js",
  "Halland, admin2": "countries/se/se-ha-all.js",
  "Jämtland, admin2": "countries/se/se-ja-all.js",
  "Jönköping, admin2": "countries/se/se-jo-all.js",
  "Kalmar, admin2": "countries/se/se-ka-all.js",
  "Kronoberg, admin2": "countries/se/se-kr-all.js",
  "Norrbotten, admin2": "countries/se/se-nb-all.js",
  "Orebro, admin2": "countries/se/se-or-all.js",
  "Östergötland, admin2": "countries/se/se-og-all.js",
  "Skåne, admin2": "countries/se/se-sn-all.js",
  "Södermanland, admin2": "countries/se/se-sd-all.js",
  "Stockholm, admin2": "countries/se/se-st-all.js",
  "Uppsala, admin2": "countries/se/se-up-all.js",
  "Värmland, admin2": "countries/se/se-vr-all.js",
  "Västerbotten, admin2": "countries/se/se-vb-all.js",
  "Västernorrland, admin2": "countries/se/se-vn-all.js",
  "Västmanland, admin2": "countries/se/se-vm-all.js",
  "Västra Götaland, admin2": "countries/se/se-vg-all.js"
};

Highcharts.mapDataIndex['Finland'] = {
  "Eastern Finland, admin2": "countries/fi/fi-3296-all.js",
  "Lapland, admin2": "countries/fi/fi-3285-all.js",
  "Oulu, admin2": "countries/fi/fi-ou-all.js",
  "Southern Finland, admin2": "countries/fi/fi-es-all.js",
  "Western Finland, admin2": "countries/fi/fi-ls-all.js"
};

Highcharts.mapDataIndex['Vietnam'] = {
  "An Giang, admin2": "countries/vn/vn-tt-all.js",
  "Bạc Liêu, admin2": "countries/vn/vn-cb-all.js",
  "Bắc Giang, admin2": "countries/vn/vn-qg-all.js",
  "Bắc Kạn, admin2": "countries/vn/vn-ls-all.js",
  "Bắc Ninh, admin2": "countries/vn/vn-5-all.js",
  "Bến Tre, admin2": "countries/vn/vn-ls-all.js",
  "Bà Rịa - Vũng Tàu, admin2": "countries/vn/vn-gl-all.js",
  "Bình Định, admin2": "countries/vn/vn-8-all.js",
  "Bình Dương, admin2": "countries/vn/vn-tg-all.js",
  "Bình Phước, admin2": "countries/vn/vn-qt-all.js",
  "Bình Thuận, admin2": "countries/vn/vn-cb-all.js",
  "Cần Thơ, admin2": "countries/vn/vn-12-all.js",
  "Cà Mau, admin2": "countries/vn/vn-ag-all.js",
  "Cao Bằng, admin2": "countries/vn/vn-tg-all.js",
  "Đắk Lắk, admin2": "countries/vn/vn-15-all.js",
  "Đắk Nông, admin2": "countries/vn/vn-do-all.js",
  "Đồng Nai, admin2": "countries/vn/vn-dn-all.js",
  "Đồng Tháp, admin2": "countries/vn/vn-tb-all.js",
  "Đà Nẵng, admin2": "countries/vn/vn-na-all.js",
  "Điện Biên, admin2": "countries/vn/vn-bi-all.js",
  "Gia Lai, admin2": "countries/vn/vn-qg-all.js",
  "Hải Dương, admin2": "countries/vn/vn-tb-all.js",
  "Hải Phòng, admin2": "countries/vn/vn-gl-all.js",
  "Hậu Giang, admin2": "countries/vn/vn-nb-all.js",
  "Hồ Chí Minh, admin2": "countries/vn/vn-dc-all.js",
  "Hà Giang, admin2": "countries/vn/vn-nb-all.js",
  "Hà Nội, admin2": "countries/vn/vn-hi-all.js",
  "Hà Nam, admin2": "countries/vn/vn-hc-all.js",
  "Hà Tĩnh, admin2": "countries/vn/vn-da-all.js",
  "Hoà Bình, admin2": "countries/vn/vn-vc-all.js",
  "Hưng Yên, admin2": "countries/vn/vn-dn-all.js",
  "Khánh Hòa, admin2": "countries/vn/vn-bn-all.js",
  "Kiên Giang, admin2": "countries/vn/vn-vc-all.js",
  "Kon Tum, admin2": "countries/vn/vn-th-all.js",
  "Lạng Sơn, admin2": "countries/vn/vn-nd-all.js",
  "Lai Châu, admin2": "countries/vn/vn-bk-all.js",
  "Lâm Đồng, admin2": "countries/vn/vn-qm-all.js",
  "Lào Cai, admin2": "countries/vn/vn-th-all.js",
  "Long An, admin2": "countries/vn/vn-nt-all.js",
  "Nam Định, admin2": "countries/vn/vn-bi-all.js",
  "Nghệ An, admin2": "countries/vn/vn-kg-all.js",
  "Ninh Bình, admin2": "countries/vn/vn-hc-all.js",
  "Ninh Thuận, admin2": "countries/vn/vn-hg-all.js",
  "Phú Thọ, admin2": "countries/vn/vn-qb-all.js",
  "Phú Yên, admin2": "countries/vn/vn-tb-all.js",
  "Quảng Bình, admin2": "countries/vn/vn-46-all.js",
  "Quảng Nam, admin2": "countries/vn/vn-hi-all.js",
  "Quảng Ngãi, admin2": "countries/vn/vn-tn-all.js",
  "Quảng Ninh, admin2": "countries/vn/vn-bv-all.js",
  "Quảng Trị, admin2": "countries/vn/vn-th-all.js",
  "Sóc Trăng, admin2": "countries/vn/vn-hd-all.js",
  "Sơn La, admin2": "countries/vn/vn-pt-all.js",
  "Tây Ninh, admin2": "countries/vn/vn-dn-all.js",
  "Thừa Thiên Huế, admin2": "countries/vn/vn-tq-all.js",
  "Thái Bình, admin2": "countries/vn/vn-55-all.js",
  "Thái Nguyên, admin2": "countries/vn/vn-hy-all.js",
  "Thanh Hóa, admin2": "countries/vn/vn-tv-all.js",
  "Tiền Giang, admin2": "countries/vn/vn-hy-all.js",
  "Trà Vinh, admin2": "countries/vn/vn-na-all.js",
  "Tuyên Quang, admin2": "countries/vn/vn-vl-all.js",
  "Vĩnh Long, admin2": "countries/vn/vn-nd-all.js",
  "Vĩnh Phúc, admin2": "countries/vn/vn-bv-all.js",
  "Yên Bái, admin2": "countries/vn/vn-pt-all.js"
};

Highcharts.mapDataIndex['Ukraine'] = {
  "Cherkasy, admin2": "countries/ua/ua-ck-all.js",
  "Chernihiv, admin2": "countries/ua/ua-ch-all.js",
  "Chernivtsi, admin2": "countries/ua/ua-cv-all.js",
  "Crimea, admin2": "countries/ua/ua-kr-all.js",
  "Dnipropetrovs'k, admin2": "countries/ua/ua-dp-all.js",
  "Donets'k, admin2": "countries/ua/ua-dt-all.js",
  "Ivano-Frankivs'k, admin2": "countries/ua/ua-if-all.js",
  "Kharkiv, admin2": "countries/ua/ua-kk-all.js",
  "Kherson, admin2": "countries/ua/ua-ks-all.js",
  "Khmel'nyts'kyy, admin2": "countries/ua/ua-km-all.js",
  "Kiev, admin2": "countries/ua/ua-kv-all.js",
  "Kiev City, admin2": "countries/ua/ua-kc-all.js",
  "Kirovohrad, admin2": "countries/ua/ua-kh-all.js",
  "L'viv, admin2": "countries/ua/ua-lv-all.js",
  "Luhans'k, admin2": "countries/ua/ua-lh-all.js",
  "Mykolayiv, admin2": "countries/ua/ua-my-all.js",
  "Odessa, admin2": "countries/ua/ua-od-all.js",
  "Poltava, admin2": "countries/ua/ua-pl-all.js",
  "Rivne, admin2": "countries/ua/ua-rv-all.js",
  "Sevastopol', admin2": "countries/ua/ua-sc-all.js",
  "Sumy, admin2": "countries/ua/ua-sm-all.js",
  "Ternopil', admin2": "countries/ua/ua-tp-all.js",
  "Transcarpathia, admin2": "countries/ua/ua-zk-all.js",
  "Vinnytsya, admin2": "countries/ua/ua-vi-all.js",
  "Volyn, admin2": "countries/ua/ua-vo-all.js",
  "Zaporizhzhya, admin2": "countries/ua/ua-zp-all.js",
  "Zhytomyr, admin2": "countries/ua/ua-zt-all.js"
};
