// https://code.highcharts.com/mapdata/
// "version": "1.1.2",

Highcharts.mapDataIndex = {
	"Custom": {
		"World": "custom/world-highres.js",
	},
	"Countries": {
		"Afghanistan": "countries/af/af-all.js",
		"Albania": "countries/al/al-all.js",
		"Algeria": "countries/dz/dz-all.js",
		"American Samoa": "countries/as/as-all.js",
		"Andorra": "countries/ad/ad-all.js",
		"Angola": "countries/ao/ao-all.js",
		"Antigua and Barbuda": "countries/ag/ag-all.js",
		"Argentina": "countries/ar/ar-all.js",
		"Armenia": "countries/am/am-all.js",
		"Australia": "countries/au/au-all.js",
		"Austria": "countries/at/at-all.js",
		"Azerbaijan": "countries/az/az-all.js",
		"Bahrain": "countries/bh/bh-all.js",
		"Bangladesh": "countries/bd/bd-all.js",
		"Barbados": "countries/bb/bb-all.js",
		"Belarus": "countries/by/by-all.js",
		"Belgium": "countries/be/be-all.js",
		"Belize": "countries/bz/bz-all.js",
		"Benin": "countries/bj/bj-all.js",
		"Bhutan": "countries/bt/bt-all.js",
		"Bolivia": "countries/bo/bo-all.js",
		"Bosnia and Herzegovina": "countries/ba/ba-all.js",
		"Botswana": "countries/bw/bw-all.js",
		"Brazil": "countries/br/br-all.js",
		"Brunei": "countries/bn/bn-all.js",
		"Bulgaria": "countries/bg/bg-all.js",
		"Burkina Faso": "countries/bf/bf-all.js",
		"Burundi": "countries/bi/bi-all.js",
		"Cambodia": "countries/kh/kh-all.js",
		"Cameroon": "countries/cm/cm-all.js",
		"Canada": "countries/ca/ca-all.js",
		"Canada, admin2": "countries/ca/ca-all-all.js",
		"Cape Verde": "countries/cv/cv-all.js",
		"Central African Republic": "countries/cf/cf-all.js",
		"Chad": "countries/td/td-all.js",
		"Chile": "countries/cl/cl-all.js",
		"China with Hong Kong and Macau": "countries/cn/custom/cn-all-sar.js",
		"China with Hong Kong, Macau, and Taiwan": "countries/cn/custom/cn-all-sar-taiwan.js",
		"China": "countries/cn/cn-all.js",
		"Colombia": "countries/co/co-all.js",
		"Comoros": "countries/km/km-all.js",
		"Cook Islands": "countries/ck/ck-all.js",
		"Costa Rica": "countries/cr/cr-all.js",
		"Croatia": "countries/hr/hr-all.js",
		"Cuba": "countries/cu/cu-all.js",
		"Cyprus": "countries/cy/cy-all.js",
		"Czech Republic": "countries/cz/cz-all.js",
		"Democratic Republic of the Congo": "countries/cd/cd-all.js",
		"Denmark": "countries/dk/dk-all.js",
		"Djibouti": "countries/dj/dj-all.js",
		"Dominica": "countries/dm/dm-all.js",
		"Dominican Republic": "countries/do/do-all.js",
		"East Timor": "countries/tl/tl-all.js",
		"Ecuador": "countries/ec/ec-all.js",
		"Egypt": "countries/eg/eg-all.js",
		"El Salvador": "countries/sv/sv-all.js",
		"Equatorial Guinea": "countries/gq/gq-all.js",
		"Eritrea": "countries/er/er-all.js",
		"Estonia": "countries/ee/ee-all.js",
		"Ethiopia": "countries/et/et-all.js",
		"Faroe Islands": "countries/fo/fo-all.js",
		"Fiji": "countries/fj/fj-all.js",
		"Finland": "countries/fi/fi-all.js",
		"France": "countries/fr/fr-all.js",
		"France, admin2": "countries/fr/fr-all-all.js",
		"France, mainland admin2": "countries/fr/custom/fr-all-all-mainland.js",
		"France, mainland": "countries/fr/custom/fr-all-mainland.js",
		"French Southern and Antarctic Lands": "countries/tf/tf-all.js",
		"Gabon": "countries/ga/ga-all.js",
		"Gambia": "countries/gm/gm-all.js",
		"Georgia": "countries/ge/ge-all.js",
		"Germany": "countries/de/de-all.js",
		"Germany, admin2": "countries/de/de-all-all.js",
		"Ghana": "countries/gh/gh-all.js",
		"Greece": "countries/gr/gr-all.js",
		"Greenland": "countries/gl/gl-all.js",
		"Grenada": "countries/gd/gd-all.js",
		"Guam": "countries/gu/gu-all.js",
		"Guatemala": "countries/gt/gt-all.js",
		"Guinea Bissau": "countries/gw/gw-all.js",
		"Guinea": "countries/gn/gn-all.js",
		"Guyana": "countries/gy/gy-all.js",
		"Haiti": "countries/ht/ht-all.js",
		"Honduras": "countries/hn/hn-all.js",
		"Hungary": "countries/hu/hu-all.js",
		"Iceland": "countries/is/is-all.js",
		"India": "countries/in/in-all.js",
		"Indonesia": "countries/id/id-all.js",
		"Iran": "countries/ir/ir-all.js",
		"Iraq": "countries/iq/iq-all.js",
		"Ireland": "countries/ie/ie-all.js",
		"Israel": "countries/il/il-all.js",
		"Italy": "countries/it/it-all.js",
		"Ivory Coast": "countries/ci/ci-all.js",
		"Jamaica": "countries/jm/jm-all.js",
		"Japan": "countries/jp/jp-all.js",
		"Jordan": "countries/jo/jo-all.js",
		"Kazakhstan": "countries/kz/kz-all.js",
		"Kenya": "countries/ke/ke-all.js",
		"Kosovo": "countries/kv/kv-all.js",
		"Kuwait": "countries/kw/kw-all.js",
		"Kyrgyzstan": "countries/kg/kg-all.js",
		"Laos": "countries/la/la-all.js",
		"Latvia": "countries/lv/lv-all.js",
		"Lebanon": "countries/lb/lb-all.js",
		"Lesotho": "countries/ls/ls-all.js",
		"Liberia": "countries/lr/lr-all.js",
		"Libya": "countries/ly/ly-all.js",
		"Liechtenstein": "countries/li/li-all.js",
		"Lithuania": "countries/lt/lt-all.js",
		"Luxembourg": "countries/lu/lu-all.js",
		"Macedonia": "countries/mk/mk-all.js",
		"Madagascar": "countries/mg/mg-all.js",
		"Malawi": "countries/mw/mw-all.js",
		"Malaysia": "countries/my/my-all.js",
		"Mali": "countries/ml/ml-all.js",
		"Malta": "countries/mt/mt-all.js",
		"Mauritania": "countries/mr/mr-all.js",
		"Mauritius": "countries/mu/mu-all.js",
		"Mexico": "countries/mx/mx-all.js",
		"Moldova": "countries/md/md-all.js",
		"Monaco": "countries/mc/mc-all.js",
		"Mongolia": "countries/mn/mn-all.js",
		"Montenegro": "countries/me/me-all.js",
		"Morocco": "countries/ma/ma-all.js",
		"Mozambique": "countries/mz/mz-all.js",
		"Myanmar": "countries/mm/mm-all.js",
		"Namibia": "countries/na/na-all.js",
		"Nauru": "countries/nr/nr-all.js",
		"Nepal": "countries/np/np-all.js",
		"New Caledonia": "countries/nc/nc-all.js",
		"New Zealand": "countries/nz/nz-all.js",
		"Nicaragua": "countries/ni/ni-all.js",
		"Niger": "countries/ne/ne-all.js",
		"Nigeria": "countries/ng/ng-all.js",
		"North Korea": "countries/kp/kp-all.js",
		"Northern Mariana Islands": "countries/mp/mp-all.js",
		"Norway": "countries/no/no-all.js",
		"Norway, admin2": "countries/no/no-all-all.js",
		"Oman": "countries/om/om-all.js",
		"Pakistan": "countries/pk/pk-all.js",
		"Palau": "countries/pw/pw-all.js",
		"Panama": "countries/pa/pa-all.js",
		"Papua New Guinea": "countries/pg/pg-all.js",
		"Paraguay": "countries/py/py-all.js",
		"Peru": "countries/pe/pe-all.js",
		"Philippines": "countries/ph/ph-all.js",
		"Poland": "countries/pl/pl-all.js",
		"Portugal": "countries/pt/pt-all.js",
		"Puerto Rico": "countries/pr/pr-all-all.js",
		"Puerto Rico": "countries/pr/pr-all.js",
		"Qatar": "countries/qa/qa-all.js",
		"Republic of Serbia": "countries/rs/rs-all.js",
		"Republic of the Congo": "countries/cg/cg-all.js",
		"Romania": "countries/ro/ro-all.js",
		"Russia with disputed territories": "countries/ru/custom/ru-all-disputed.js",
		"Russia": "countries/ru/ru-all.js",
		"Rwanda": "countries/rw/rw-all.js",
		"Saint Kitts and Nevis": "countries/kn/kn-all.js",
		"Saint Lucia": "countries/lc/lc-all.js",
		"Saint Vincent and the Grenadines": "countries/vc/vc-all.js",
		"Samoa": "countries/ws/ws-all.js",
		"San Marino": "countries/sm/sm-all.js",
		"Sao Tome and Principe": "countries/st/st-all.js",
		"Saudi Arabia": "countries/sa/sa-all.js",
		"Senegal": "countries/sn/sn-all.js",
		"Seychelles": "countries/sc/sc-all.js",
		"Sierra Leone": "countries/sl/sl-all.js",
		"Singapore": "countries/sg/sg-all.js",
		"Slovakia": "countries/sk/sk-all.js",
		"Slovenia": "countries/si/si-all.js",
		"Solomon Islands": "countries/sb/sb-all.js",
		"Somalia": "countries/so/so-all.js",
		"Somaliland": "countries/sx/sx-all.js",
		"South Africa": "countries/za/za-all.js",
		"South Korea": "countries/kr/kr-all.js",
		"South Sudan": "countries/ss/ss-all.js",
		"Spain": "countries/es/es-all.js",
		"Sri Lanka": "countries/lk/lk-all.js",
		"Sudan": "countries/sd/sd-all.js",
		"Suriname": "countries/sr/sr-all.js",
		"Swaziland": "countries/sz/sz-all.js",
		"Sweden": "countries/se/se-all.js",
		"Switzerland": "countries/ch/ch-all.js",
		"Syria": "countries/sy/sy-all.js",
		"Taiwan": "countries/tw/tw-all.js",
		"Tajikistan": "countries/tj/tj-all.js",
		"Thailand": "countries/th/th-all.js",
		"The Bahamas": "countries/bs/bs-all.js",
		"The Netherlands": "countries/nl/nl-all.js",
		"The Netherlands, admin2": "countries/nl/nl-all-all.js",
		"Togo": "countries/tg/tg-all.js",
		"Trinidad and Tobago": "countries/tt/tt-all.js",
		"Tunisia": "countries/tn/tn-all.js",
		"Turkey": "countries/tr/tr-all.js",
		"Turkmenistan": "countries/tm/tm-all.js",
		"Uganda": "countries/ug/ug-all.js",
		"Ukraine": "countries/ua/ua-all.js",
		"United Arab Emirates": "countries/ae/ae-all.js",
		"United Kingdom": "countries/gb/custom/gb-countries.js",
		"United Republic of Tanzania": "countries/tz/tz-all.js",
		"United States Virgin Islands": "countries/vi/vi-all.js",
		"United States of America with Territories": "countries/us/custom/us-all-territories.js",
		"United States of America": "countries/us/us-all.js",
		"United States of America, admin2": "countries/us/us-all-all.js",
		"United States of America, admin2, highres": "countries/us/us-all-all-highres.js",
		"United States of America, congressional districts (113th)": "countries/us/custom/us-113-congress.js",
		"United States of America, mainland": "countries/us/custom/us-all-mainland.js",
		"United States of America, small": "countries/us/custom/us-small.js",
		"Uruguay": "countries/uy/uy-all.js",
		"Uzbekistan": "countries/uz/uz-all.js",
		"Vanuatu": "countries/vu/vu-all.js",
		"Venezuela": "countries/ve/ve-all.js",
		"Vietnam": "countries/vn/vn-all.js",
		"Wallis and Futuna": "countries/wf/wf-all.js",
		"Western Sahara": "countries/eh/eh-all.js",
		"Yemen": "countries/ye/ye-all.js",
		"Zambia": "countries/zm/zm-all.js",
		"Zimbabwe": "countries/zw/zw-all.js"
	},
	"Canada Provinces Admin 2": {
		"Alberta, admin2": "countries/ca/ca-ab-all.js",
		"British Columbia, admin2": "countries/ca/ca-bc-all.js",
		"Manitoba, admin2": "countries/ca/ca-mb-all.js",
		"New Brunswick, admin2": "countries/ca/ca-nb-all.js",
		"Newfoundland and Labrador, admin2": "countries/ca/ca-nf-all.js",
		"Northwest Territories, admin2": "countries/ca/ca-nt-all.js",
		"Nova Scotia, admin2": "countries/ca/ca-ns-all.js",
		"Nunavut, admin2": "countries/ca/ca-nu-all.js",
		"Ontario, admin2": "countries/ca/ca-on-all.js",
		"Prince Edward Island, admin2": "countries/ca/ca-pe-all.js",
		"Quebec, admin2": "countries/ca/ca-qc-all.js",
		"Saskatchewan, admin2": "countries/ca/ca-sk-all.js",
		"Yukon, admin2": "countries/ca/ca-yt-all.js"
	},
	"France Regions Admin 2": {
		"Alsace, admin2": "countries/fr/fr-a-all.js",
		"Aquitaine, admin2": "countries/fr/fr-b-all.js",
		"Auvergne, admin2": "countries/fr/fr-c-all.js",
		"Basse-Normandie, admin2": "countries/fr/fr-p-all.js",
		"Bourgogne, admin2": "countries/fr/fr-d-all.js",
		"Bretagne, admin2": "countries/fr/fr-e-all.js",
		"Centre, admin2": "countries/fr/fr-f-all.js",
		"Champagne-Ardenne, admin2": "countries/fr/fr-g-all.js",
		"Corse, admin2": "countries/fr/fr-h-all.js",
		"Franche-Comté, admin2": "countries/fr/fr-i-all.js",
		"Guadeloupe, admin2": "countries/fr/fr-gp-all.js",
		"Guyane française, admin2": "countries/fr/fr-gf-all.js",
		"Haute-Normandie, admin2": "countries/fr/fr-q-all.js",
		"Languedoc-Roussillon, admin2": "countries/fr/fr-k-all.js",
		"Limousin, admin2": "countries/fr/fr-l-all.js",
		"Lorraine, admin2": "countries/fr/fr-m-all.js",
		"Martinique, admin2": "countries/fr/fr-mq-all.js",
		"Mayotte, admin2": "countries/fr/fr-yt-all.js",
		"Midi-Pyrénées, admin2": "countries/fr/fr-n-all.js",
		"Nord-Pas-de-Calais, admin2": "countries/fr/fr-o-all.js",
		"Pays de la Loire, admin2": "countries/fr/fr-r-all.js",
		"Picardie, admin2": "countries/fr/fr-s-all.js",
		"Poitou-Charentes, admin2": "countries/fr/fr-t-all.js",
		"Provence-Alpes-Côte-d'Azur, admin2": "countries/fr/fr-u-all.js",
		"Rhône-Alpes, admin2": "countries/fr/fr-v-all.js",
		"Réunion, admin2": "countries/fr/fr-re-all.js",
		"Île-de-France, admin2": "countries/fr/fr-j-all.js"
	},
	"Germany Bundesländer Admin 2": {
		"Baden-Württemberg, admin2": "countries/de/de-bw-all.js",
		"Bayern, admin2": "countries/de/de-by-all.js",
		"Berlin, admin2": "countries/de/de-be-all.js",
		"Brandenburg, admin2": "countries/de/de-bb-all.js",
		"Bremen, admin2": "countries/de/de-hb-all.js",
		"Hamburg, admin2": "countries/de/de-hh-all.js",
		"Hessen, admin2": "countries/de/de-he-all.js",
		"Mecklenburg-Vorpommern, admin2": "countries/de/de-mv-all.js",
		"Niedersachsen, admin2": "countries/de/de-ni-all.js",
		"Nordrhein-Westfalen, admin2": "countries/de/de-nw-all.js",
		"Rheinland-Pfalz, admin2": "countries/de/de-rp-all.js",
		"Saarland, admin2": "countries/de/de-sl-all.js",
		"Sachsen, admin2": "countries/de/de-sn-all.js",
		"Sachsen-Anhalt, admin2": "countries/de/de-st-all.js",
		"Schleswig-Holstein, admin2": "countries/de/de-sh-all.js",
		"Thüringen, admin2": "countries/de/de-th-all.js"
	},
	"Netherlands Provinces": {
		"Drenthe, admin2": "countries/nl/nl-dr-all.js",
		"Flevoland, admin2": "countries/nl/nl-fl-all.js",
		"Friesland, admin2": "countries/nl/nl-fr-all.js",
		"Gelderland, admin2": "countries/nl/nl-ge-all.js",
		"Groningen, admin2": "countries/nl/nl-gr-all.js",
		"Limburg, admin2": "countries/nl/nl-li-all.js",
		"Noord-Brabant, admin2": "countries/nl/nl-nb-all.js",
		"Noord-Holland, admin2": "countries/nl/nl-nh-all.js",
		"Overijssel, admin2": "countries/nl/nl-ov-all.js",
		"Utrecht, admin2": "countries/nl/nl-ut-all.js",
		"Zeeland, admin2": "countries/nl/nl-ze-all.js",
		"Zuid-Holland, admin2": "countries/nl/nl-zh-all.js"
	},
	"Norway Counties": {
		"Akershus, admin2": "countries/no/no-ak-all.js",
		"Aust-Agder, admin2": "countries/no/no-aa-all.js",
		"Buskerud, admin2": "countries/no/no-bu-all.js",
		"Finnmark, admin2": "countries/no/no-fi-all.js",
		"Hedmark, admin2": "countries/no/no-he-all.js",
		"Hordaland, admin2": "countries/no/no-ho-all.js",
		"Møre og Romsdal, admin2": "countries/no/no-mr-all.js",
		"Nord-Trøndelag, admin2": "countries/no/no-nt-all.js",
		"Nordland, admin2": "countries/no/no-no-all.js",
		"Oppland, admin2": "countries/no/no-op-all.js",
		"Oslo, admin2": "countries/no/no-os-all.js",
		"Rogaland, admin2": "countries/no/no-ro-all.js",
		"Sogn og Fjordane, admin2": "countries/no/no-sf-all.js",
		"Sør-Trøndelag, admin2": "countries/no/no-st-all.js",
		"Telemark, admin2": "countries/no/no-te-all.js",
		"Troms, admin2": "countries/no/no-tr-all.js",
		"Vest-Agder, admin2": "countries/no/no-va-all.js",
		"Vestfold, admin2": "countries/no/no-vf-all.js",
		"Østfold, admin2": "countries/no/no-of-all.js"
	},
	"USA States": {
		"Alabama, admin2": "countries/us/us-al-all.js",
		"Alaska, admin2": "countries/us/us-ak-all.js",
		"Arizona, admin2": "countries/us/us-az-all.js",
		"Arkansas, admin2": "countries/us/us-ar-all.js",
		"California, admin2": "countries/us/us-ca-all.js",
		"Colorado, admin2": "countries/us/us-co-all.js",
		"Connecticut, admin2": "countries/us/us-ct-all.js",
		"Delaware, admin2": "countries/us/us-de-all.js",
		"District of Columbia, admin2": "countries/us/us-dc-all.js",
		"Florida, admin2": "countries/us/us-fl-all.js",
		"Georgia, admin2": "countries/us/us-ga-all.js",
		"Hawaii, admin2": "countries/us/us-hi-all.js",
		"Idaho, admin2": "countries/us/us-id-all.js",
		"Illinois, admin2": "countries/us/us-il-all.js",
		"Indiana, admin2": "countries/us/us-in-all.js",
		"Iowa, admin2": "countries/us/us-ia-all.js",
		"Kansas, admin2": "countries/us/us-ks-all.js",
		"Kentucky, admin2": "countries/us/us-ky-all.js",
		"Louisiana, admin2": "countries/us/us-la-all.js",
		"Maine, admin2": "countries/us/us-me-all.js",
		"Maryland, admin2": "countries/us/us-md-all.js",
		"Massachusetts, admin2": "countries/us/us-ma-all.js",
		"Michigan, admin2": "countries/us/us-mi-all.js",
		"Minnesota, admin2": "countries/us/us-mn-all.js",
		"Mississippi, admin2": "countries/us/us-ms-all.js",
		"Missouri, admin2": "countries/us/us-mo-all.js",
		"Montana, admin2": "countries/us/us-mt-all.js",
		"Nebraska, admin2": "countries/us/us-ne-all.js",
		"Nevada, admin2": "countries/us/us-nv-all.js",
		"New Hampshire, admin2": "countries/us/us-nh-all.js",
		"New Jersey, admin2": "countries/us/us-nj-all.js",
		"New Mexico, admin2": "countries/us/us-nm-all.js",
		"New York, admin2": "countries/us/us-ny-all.js",
		"North Carolina, admin2": "countries/us/us-nc-all.js",
		"North Dakota, admin2": "countries/us/us-nd-all.js",
		"Ohio, admin2": "countries/us/us-oh-all.js",
		"Oklahoma, admin2": "countries/us/us-ok-all.js",
		"Oregon, admin2": "countries/us/us-or-all.js",
		"Pennsylvania, admin2": "countries/us/us-pa-all.js",
		"Rhode Island, admin2": "countries/us/us-ri-all.js",
		"South Carolina, admin2": "countries/us/us-sc-all.js",
		"South Dakota, admin2": "countries/us/us-sd-all.js",
		"Tennessee, admin2": "countries/us/us-tn-all.js",
		"Texas, admin2": "countries/us/us-tx-all.js",
		"Utah, admin2": "countries/us/us-ut-all.js",
		"Vermont, admin2": "countries/us/us-vt-all.js",
		"Virginia, admin2": "countries/us/us-va-all.js",
		"Washington, admin2": "countries/us/us-wa-all.js",
		"West Virginia, admin2": "countries/us/us-wv-all.js",
		"Wisconsin, admin2": "countries/us/us-wi-all.js",
		"Wyoming, admin2": "countries/us/us-wy-all.js"
	}
};

Highcharts.mapDataIndex['Denmark Admin 2'] = {
  'Nordjylland, admin2': 'countries/dk/dk-3568-all.js',
  'Midtjylland, admin2': 'countries/dk/dk-6326-all.js',
  'Syddanmark, admin2': 'countries/dk/dk-3564-all.js',
  'Sjælland, admin2': 'countries/dk/dk-3563-all.js',
  'Hovedstaden, admin2': 'countries/dk/dk-6325-all.js'
};

Highcharts.mapDataIndex['Sweden Admin 2'] = {
  "Blekinge, admin2": "countries/se/se-bl-all.js",
  "Dalarna, admin2": "countries/se/se-ko-all.js",
  "Gävleborg, admin2": "countries/se/se-gv-all.js",
  "Gotland, admin2": "countries/se/se-gt-all.js",
  "Halland, admin2": "countries/se/se-ha-all.js",
  "Jämtland, admin2": "countries/se/se-ja-all.js",
  "Jönköping, admin2": "countries/se/se-jo-all.js",
  "Kalmar, admin2": "countries/se/se-ka-all.js",
  "Kronoberg, admin2": "countries/se/se-kr-all.js",
  "Norrbotten, admin2": "countries/se/se-nb-all.js",
  "Orebro, admin2": "countries/se/se-or-all.js",
  "Östergötland, admin2": "countries/se/se-og-all.js",
  "Skåne, admin2": "countries/se/se-sn-all.js",
  "Södermanland, admin2": "countries/se/se-sd-all.js",
  "Stockholm, admin2": "countries/se/se-st-all.js",
  "Uppsala, admin2": "countries/se/se-up-all.js",
  "Värmland, admin2": "countries/se/se-vr-all.js",
  "Västerbotten, admin2": "countries/se/se-vb-all.js",
  "Västernorrland, admin2": "countries/se/se-vn-all.js",
  "Västmanland, admin2": "countries/se/se-vm-all.js",
  "Västra Götaland, admin2": "countries/se/se-vg-all.js"
};

Highcharts.mapDataIndex['Finland Admin 2'] = {
	"Eastern Finland, admin2": "countries/fi/fi-is-all.js",
	"Lapland, admin2": "countries/fi/fi-lp-all.js",
	"Norra Finlands, admin2": "countries/fi/fi-ou-all.js",
	"Etelä-Suomen, admin2": "countries/fi/fi-es-all.js",
	"Western Finland, admin2": "countries/fi/fi-ls-all.js"
};

Highcharts.mapDataIndex['United Kingdom Admin 2'] = {
  "England, admin2": "countries/gb/gb-eng-all.js",
  "Northern Ireland, admin2": "countries/gb/gb-nir-all.js",
  "Scotland, admin2": "countries/gb/gb-sct-all.js",
  "Wales, admin2": "countries/gb/gb-wls-all.js"
};

Highcharts.mapDataIndex['Vietnam Admin 2'] = {
  "An Giang, admin2": "countries/vn/vn-ag-all.js",
  "Bạc Liêu, admin2": "countries/vn/vn-bl-all.js",
  "Bắc Giang, admin2": "countries/vn/vn-bg-all.js",
  "Bắc Kạn, admin2": "countries/vn/vn-bk-all.js",
  "Bắc Ninh, admin2": "countries/vn/vn-bn-all.js",
  "Bến Tre, admin2": "countries/vn/vn-br-all.js",
  "Bà Rịa - Vũng Tàu, admin2": "countries/vn/vn-bv-all.js",
  "Bình Định, admin2": "countries/vn/vn-bd-all.js",
  "Bình Dương, admin2": "countries/vn/vn-bi-all.js",
  "Bình Phước, admin2": "countries/vn/vn-bp-all.js",
  "Bình Thuận, admin2": "countries/vn/vn-bu-all.js",
  "Cần Thơ, admin2": "countries/vn/vn-12-all.js",
  "Cà Mau, admin2": "countries/vn/vn-cm-all.js",
  "Cao Bằng, admin2": "countries/vn/vn-cb-all.js",
  "Đắk Lắk, admin2": "countries/vn/vn-dl-all.js",
  "Đắk Nông, admin2": "countries/vn/vn-dn-all.js",
  "Đồng Nai, admin2": "countries/vn/vn-di-all.js",
  "Đồng Tháp, admin2": "countries/vn/vn-dt-all.js",
  "Đà Nẵng, admin2": "countries/vn/vn-da-all.js",
  "Điện Biên, admin2": "countries/vn/vn-db-all.js",
  "Gia Lai, admin2": "countries/vn/vn-gl-all.js",
  "Hải Dương, admin2": "countries/vn/vn-hd-all.js",
  "Hải Phòng, admin2": "countries/vn/vn-hp-all.js",
  "Hậu Giang, admin2": "countries/vn/vn-24-all.js",
  "Hồ Chí Minh, admin2": "countries/vn/vn-hc-all.js",
  "Hà Giang, admin2": "countries/vn/vn-hg-all.js",
  "Hà Nội, admin2": "countries/vn/vn-hn-all.js",
  "Hà Nam, admin2": "countries/vn/vn-hm-all.js",
  "Hà Tĩnh, admin2": "countries/vn/vn-ht-all.js",
  "Hoà Bình, admin2": "countries/vn/vn-ho-all.js",
  "Hưng Yên, admin2": "countries/vn/vn-hy-all.js",
  "Khánh Hòa, admin2": "countries/vn/vn-kh-all.js",
  "Kiên Giang, admin2": "countries/vn/vn-kg-all.js",
  "Kon Tum, admin2": "countries/vn/vn-kt-all.js",
  "Lạng Sơn, admin2": "countries/vn/vn-ls-all.js",
  "Lai Châu, admin2": "countries/vn/vn-li-all.js",
  "Lâm Đồng, admin2": "countries/vn/vn-ld-all.js",
  "Lào Cai, admin2": "countries/vn/vn-lo-all.js",
  "Long An, admin2": "countries/vn/vn-la-all.js",
  "Nam Định, admin2": "countries/vn/vn-nd-all.js",
  "Nghệ An, admin2": "countries/vn/vn-na-all.js",
  "Ninh Bình, admin2": "countries/vn/vn-nb-all.js",
  "Ninh Thuận, admin2": "countries/vn/vn-nt-all.js",
  "Phú Thọ, admin2": "countries/vn/vn-pt-all.js",
  "Phú Yên, admin2": "countries/vn/vn-py-all.js",
  "Quảng Bình, admin2": "countries/vn/vn-qb-all.js",
  "Quảng Nam, admin2": "countries/vn/vn-qa-all.js",
  "Quảng Ngãi, admin2": "countries/vn/vn-qg-all.js",
  "Quảng Ninh, admin2": "countries/vn/vn-qn-all.js",
  "Quảng Trị, admin2": "countries/vn/vn-qt-all.js",
  "Sóc Trăng, admin2": "countries/vn/vn-st-all.js",
  "Sơn La, admin2": "countries/vn/vn-sl-all.js",
  "Tây Ninh, admin2": "countries/vn/vn-tn-all.js",
  "Thừa Thiên Huế, admin2": "countries/vn/vn-tt-all.js",
  "Thái Bình, admin2": "countries/vn/vn-tb-all.js",
  "Thái Nguyên, admin2": "countries/vn/vn-ty-all.js",
  "Thanh Hóa, admin2": "countries/vn/vn-th-all.js",
  "Tiền Giang, admin2": "countries/vn/vn-tg-all.js",
  "Trà Vinh, admin2": "countries/vn/vn-tv-all.js",
  "Tuyên Quang, admin2": "countries/vn/vn-tq-all.js",
  "Vĩnh Long, admin2": "countries/vn/vn-vl-all.js",
  "Vĩnh Phúc, admin2": "countries/vn/vn-vc-all.js",
  "Yên Bái, admin2": "countries/vn/vn-yb-all.js"
};

Highcharts.mapDataIndex['Ukraine Admin 2'] = {
  "Cherkasy, admin2": "countries/ua/ua-ck-all.js",
  "Chernihiv, admin2": "countries/ua/ua-ch-all.js",
  "Chernivtsi, admin2": "countries/ua/ua-cv-all.js",
  "Crimea, admin2": "countries/ua/ua-kr-all.js",
  "Dnipropetrovs'k, admin2": "countries/ua/ua-dp-all.js",
  "Donets'k, admin2": "countries/ua/ua-dt-all.js",
  "Ivano-Frankivs'k, admin2": "countries/ua/ua-if-all.js",
  "Kharkiv, admin2": "countries/ua/ua-kk-all.js",
  "Kherson, admin2": "countries/ua/ua-ks-all.js",
  "Khmel'nyts'kyy, admin2": "countries/ua/ua-km-all.js",
  "Kiev, admin2": "countries/ua/ua-kv-all.js",
  "Kiev City, admin2": "countries/ua/ua-kc-all.js",
  "Kirovohrad, admin2": "countries/ua/ua-kh-all.js",
  "L'viv, admin2": "countries/ua/ua-lv-all.js",
  "Luhans'k, admin2": "countries/ua/ua-lh-all.js",
  "Mykolayiv, admin2": "countries/ua/ua-my-all.js",
  "Odessa, admin2": "countries/ua/ua-od-all.js",
  "Poltava, admin2": "countries/ua/ua-pl-all.js",
  "Rivne, admin2": "countries/ua/ua-rv-all.js",
  "Sevastopol', admin2": "countries/ua/ua-sc-all.js",
  "Sumy, admin2": "countries/ua/ua-sm-all.js",
  "Ternopil', admin2": "countries/ua/ua-tp-all.js",
  "Transcarpathia, admin2": "countries/ua/ua-zk-all.js",
  "Vinnytsya, admin2": "countries/ua/ua-vi-all.js",
  "Volyn, admin2": "countries/ua/ua-vo-all.js",
  "Zaporizhzhya, admin2": "countries/ua/ua-zp-all.js",
  "Zhytomyr, admin2": "countries/ua/ua-zt-all.js"
};
